/**
 * Aset 3D Microsoft Fluent Emoji (MIT) di public/assets/3d/<nama>-<64|128|256>.webp.
 * Daftar ini harus sama dengan FLUENT_FOLDERS di scripts/assets/build-3d.mjs (dijaga tes asset-3d).
 */
export const ASSET_3D_NAMES = [
  "abacus",
  "airplane",
  "alarm-clock",
  "automobile",
  "baby-bottle",
  "balance-scale",
  "bank",
  "bar-chart",
  "bell",
  "books",
  "briefcase",
  "bullseye",
  "bus",
  "chart-increasing",
  "check-mark-button",
  "classical-building",
  "clipboard",
  "closed-mailbox-with-lowered-flag",
  "coin",
  "convenience-store",
  "counterclockwise-arrows-button",
  "credit-card",
  "dollar-banknote",
  "droplet",
  "envelope",
  "fork-and-knife-with-plate",
  "fuel-pump",
  "gear",
  "gem-stone",
  "globe-with-meridians",
  "graduation-cap",
  "high-voltage",
  "hot-beverage",
  "house",
  "house-with-garden",
  "inbox-tray",
  "key",
  "label",
  "ledger",
  "left-right-arrow",
  "light-bulb",
  "memo",
  "mobile-phone",
  "money-bag",
  "money-with-wings",
  "motor-scooter",
  "motorway",
  "musical-notes",
  "open-file-folder",
  "package",
  "page-facing-up",
  "party-popper",
  "paw-prints",
  "people-hugging",
  "pill",
  "popcorn",
  "purse",
  "receipt",
  "red-envelope",
  "repeat-button",
  "running-shoe",
  "satellite-antenna",
  "seedling",
  "shopping-bags",
  "shopping-cart",
  "spiral-calendar",
  "steaming-bowl",
  "t-shirt",
  "triangular-flag",
  "trophy",
  "wrapped-gift",
] as const;

export type Asset3DName = (typeof ASSET_3D_NAMES)[number];

/** Lebar berkas yang tersedia per aset; 256 adalah ukuran asli Fluent. */
export const ASSET_3D_WIDTHS = [64, 128, 256] as const;

export function asset3dSrc(name: Asset3DName, width: (typeof ASSET_3D_WIDTHS)[number]): string {
  return `/assets/3d/${name}-${width}.webp`;
}
