import {
  ArrowLeftRight,
  Baby,
  Banknote,
  Bike,
  BookOpen,
  Briefcase,
  Bus,
  Car,
  Circle,
  CircleEllipsis,
  Clapperboard,
  Coffee,
  Droplet,
  Dumbbell,
  FileText,
  Fuel,
  Gift,
  GraduationCap,
  HeartPulse,
  House,
  KeyRound,
  Landmark,
  PawPrint,
  PiggyBank,
  Plane,
  Receipt,
  Scale,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  Smartphone,
  Sparkles,
  SquareParking,
  Store,
  TrendingUp,
  Undo2,
  Users,
  Utensils,
  UtensilsCrossed,
  Wallet,
  Wifi,
  Zap,
  type LucideIcon,
} from "lucide-react";

/** Ikon kategori yang bisa dipilih; kunci = nama Lucide kebab-case yang disimpan di categories.icon. */
export const CATEGORY_ICONS: ReadonlyArray<{ key: string; label: string; icon: LucideIcon }> = [
  { key: "utensils", label: "Makan", icon: Utensils },
  { key: "utensils-crossed", label: "Makan di luar", icon: UtensilsCrossed },
  { key: "shopping-basket", label: "Belanja dapur", icon: ShoppingBasket },
  { key: "coffee", label: "Kopi", icon: Coffee },
  { key: "car", label: "Mobil", icon: Car },
  { key: "bike", label: "Motor", icon: Bike },
  { key: "bus", label: "Angkutan umum", icon: Bus },
  { key: "fuel", label: "Bensin", icon: Fuel },
  { key: "square-parking", label: "Parkir", icon: SquareParking },
  { key: "plane", label: "Perjalanan", icon: Plane },
  { key: "house", label: "Rumah", icon: House },
  { key: "key-round", label: "Sewa", icon: KeyRound },
  { key: "zap", label: "Listrik", icon: Zap },
  { key: "droplet", label: "Air", icon: Droplet },
  { key: "wifi", label: "Internet", icon: Wifi },
  { key: "smartphone", label: "Pulsa", icon: Smartphone },
  { key: "receipt", label: "Tagihan", icon: Receipt },
  { key: "heart-pulse", label: "Kesehatan", icon: HeartPulse },
  { key: "dumbbell", label: "Olahraga", icon: Dumbbell },
  { key: "graduation-cap", label: "Pendidikan", icon: GraduationCap },
  { key: "book-open", label: "Buku", icon: BookOpen },
  { key: "shopping-bag", label: "Belanja", icon: ShoppingBag },
  { key: "shirt", label: "Pakaian", icon: Shirt },
  { key: "clapperboard", label: "Hiburan", icon: Clapperboard },
  { key: "gift", label: "Hadiah", icon: Gift },
  { key: "users", label: "Keluarga", icon: Users },
  { key: "baby", label: "Anak", icon: Baby },
  { key: "paw-print", label: "Hewan peliharaan", icon: PawPrint },
  { key: "landmark", label: "Bank", icon: Landmark },
  { key: "file-text", label: "Dokumen", icon: FileText },
  { key: "briefcase", label: "Kerja", icon: Briefcase },
  { key: "sparkles", label: "Bonus", icon: Sparkles },
  { key: "store", label: "Usaha", icon: Store },
  { key: "trending-up", label: "Imbal hasil", icon: TrendingUp },
  { key: "piggy-bank", label: "Tabungan", icon: PiggyBank },
  { key: "wallet", label: "Uang saku", icon: Wallet },
  { key: "banknote", label: "Uang tunai", icon: Banknote },
  { key: "undo-2", label: "Pengembalian", icon: Undo2 },
  { key: "circle-ellipsis", label: "Lainnya", icon: CircleEllipsis },
  { key: "circle", label: "Umum", icon: Circle },
];

// ikon kategori sistem; tidak bisa dipilih pengguna
const SYSTEM_ICONS: Record<string, LucideIcon> = { scale: Scale, "arrow-left-right": ArrowLeftRight };

const BY_KEY = new Map(CATEGORY_ICONS.map((entry) => [entry.key, entry.icon]));

export function categoryIcon(key: string): LucideIcon {
  return BY_KEY.get(key) ?? SYSTEM_ICONS[key] ?? Circle;
}
